version: '3.8'

services:
  web:
    build: .
    command: run_service.sh
    volumes:
      - .:/docusketch
    ports:
      - "8080:5000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
